name: Apple Pen

on:
  repository_dispatch:
    types:
      - ppap
      - dev-*
      - dev-*
      - dev-*
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  REF_NAME: ${{ github.event.client_payload.ref_name }}
  TRIGGERING_ACTOR: ${{ github.event.client_payload.triggering_actor }}
  MAIN_REPOSITORY: ${{ secrets.CUCU_REPOSITORY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_GROUP_ID: ${{ vars.TELEGRAM_GROUP_ID }}
  TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID }}
  API_KEY_JSON: ${{ secrets.API_KEY_JSON }}
  PRO_PLAY_STORE_KEY_JSON: ${{ secrets.PRO_PLAY_STORE_KEY_JSON }}
  PRO_API_KEY_JSON: ${{secrets.PRO_API_KEY_JSON}}
  FIREBASE_CLI_TOKEN: ${{secrets.PRO_FIREBASE_CLI_TOKEN}}
  ANDROID_FIREBASE_ID: ${{secrets.PRO_ANDROID_FIREBASE_ID}}
  PRO_GOOGLESERVICE_INFO_PLIST: ${{secrets.PRO_GOOGLESERVICE_INFO_PLIST}}
  PRO_GOOGLE_SERVICES_JSON: ${{secrets.PRO_GOOGLE_SERVICES_JSON}}
  PROD_RELEASE_KEYSTORE_BASE64: ${{secrets.PROD_RELEASE_KEYSTORE_BASE64}}
  DYNAMIC_CONSTANTS_TS_PROD_BASE64: ${{secrets.DYNAMIC_CONSTANTS_TS_PROD_BASE64}}

jobs:
  init:
    name: Init
    runs-on: macos-14
    outputs:
      matrix: ${{ steps.set-matrix.outputs.value }}
      message-information: ${{ steps.get-message-information.outputs.value }}
      env: ${{ steps.set-env.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MAIN_REPOSITORY }}
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref_name}}
        if: vars.IS_SILENT != 'true'
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: "🎬 -  Start build: ${{ steps.get-message-information.outputs.value }}"
